### ISSUE TITLE
uptest e2e fails when namespaced is not specified for the namespaced Claim

### ISSUE THREAD

**Issue by ytsarev** [upbound/uptest#38]
### What happened?

The `uptest e2e` is ambiguously failing when the `namespace` is not specified for a namespaced `Claim`

### How can we reproduce it?

Consider the `Claim` example from https://github.com/upbound/platform-ref-gcp/pull/39

```
cat examples/cluster-claim.yaml
apiVersion: gcp.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-gcp-cluster
  namespace: default
  annotations:
    uptest.upbound.io/pre-delete-hook: testhooks/delete-release.sh
spec:
 ....
```

If we remove explicit `namespace: default` from this `Claim` it will make uptest failing

```
   logger.go:42: 16:10:19 | case/0-apply | Error from server (NotFound): postgresqlinstances.gcp.platformref.upbound.io "platform-ref-gcp-db" not found
```

as the assert will treat it as cluster-scoped resource

```
cat case/01-assert.yaml
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 2400
commands:
- command: ${KUBECTL} wait cluster.gcp.platformref.upbound.io/platform-ref-gcp-cluster --for=delete --timeout 10s --namespace default
- command: ${KUBECTL} wait postgresqlinstance.gcp.platformref.upbound.io/platform-ref-gcp-db --for=delete --timeout 10s
- command: ${KUBECTL} wait managed --all --for=delete --timeout 10s
```

meanwhile, the Claim will be put into the  automatically generated namespace

```
k get claim -A
NAMESPACE              NAME                                                                READY   CONNECTION-SECRET          AGE
kuttl-test-good-crow   postgresqlinstance.gcp.platformref.upbound.io/platform-ref-gcp-db   True    platform-ref-gcp-db-conn   47m
```

### Possible solutions

* teach `uptest` to construct assert with automatically generated namespace
* just document the need of explicit `namespace` specification for the namespace resources

### What environment did it happen in?

* `universal-crossplane-1.9.1-up.2`
* uptest `v0.2.0`
