### ISSUE TITLE
testing: format of datasource.yaml files

### ISSUE THREAD

**Issue by sergenyalcin** [upbound/uptest#9]
### What problem are you facing?

In some example manifests, we need to inject some values e.g `tenantID`, `accountID`, `objectID`. This injection values usually corresponds to Data Sources of Terraform. Please see the following example:

`tenantId: ${data.azurerm_client_config.current.tenant_id}`

This convention is from the Terraform registry documentation. So we use a regular expression to extract the key of the tenantID value. For this example ,the key is: `azurerm_client_config.current.tenant_id`

And our source yaml file has the following format:

```yaml
azurerm_client_config.current.tenant_id: ***
azurerm_client_config.current.object_id: ***
```

@muvaf suggested two formats for data source yaml in this [PR]: https://github.com/upbound/official-providers/pull/299#discussion_r910804037

```yaml
data:
  azurerm_client_config:
    current:
      object_id: 847c7043-b0a5-4fdf-9285-ee084c94a206
```

```yaml
azure:
  tenantId: b9925bc4-8383-4c37-b9d2-fa456d1bb1c7
  objectId: 847c7043-b0a5-4fdf-9285-ee084c94a206
```

[PR]: https://github.com/upbound/official-providers/pull/299

### How could Official Providers help solve your problem?

Let's discuss the possible formats and decide that a best one.
